### ISSUE TITLE
Tag and build multiple versions

### ISSUE THREAD

**Issue by darkdragon-001** [mviereck/dockerfile-x11docker-xfce#1]
I often stumble over some software which worked in a previous version. x11docker could be a great tool to test in which version it stopped working. Therefore, it would be nice, if you could tag versions (e.g. `x11docker/xfce:4-buster` for Xfce 4 on Debian Buster) and publish them on hub.docker.com.

**Comment by mviereck** [comment]
Thank you for your suggestion!
I would not like to maintain multiple tags for this (or all) desktop images.
At least I have to rebuild them every few month to keep them half-way up to date with security fixes. 

If you like to test applications with different Debian versions, you can build images directly based e.g. on `debian:buster` or `debian:stretch` and would not need Xfce.

If you like to test with different Xfce versions, it might be better to build images that directly provide several Xfce versions. Debian only provides a subset of Xfce versions depending on the Debian release cycle.

**Comment by darkdragon-001** [comment]
In hub.docker.com, you can define _Build triggers_ which is an HTTP/POST endpoint which you just have to call (e.g. via `curl`) to trigger a rebuild. So building images is as easy as setting up a cronjob...

I would like to start right away, with a base image including all common dependencies (especially GUI libraries which are not included in default images). Usually, I just do `docker run -it --rm ubuntu:VERSION` and in container I install dependencies and run the application. But for GUI applications I need the GUI dependencies which take some time to install and all the forwarding has to be setup. I just thought it might be easier to use x11docker for that...

**Comment by mviereck** [comment]
> In hub.docker.com, you can define Build triggers which is an HTTP/POST endpoint which you just have to call (e.g. via curl) to trigger a rebuild. So building images is as easy as setting up a cronjob...

Thank you for the hint! I'll look at that.

> But for GUI applications I need the GUI dependencies which take some time to install and all the forwarding has to be setup. I just thought it might be easier to use x11docker for that...

Couldn't you just set up a tagged docker hub repo yourself?
Take e.g. the `x11docker/xfce` Dockerfile, adjust it and set up a repo with several tags matching your needs. It might be based on several Debian versions as well as other distros like alpine, too.

**Comment by darkdragon-001** [comment]
> > In hub.docker.com, you can define Build triggers which is an HTTP/POST endpoint which you just have to call (e.g. via curl) to trigger a rebuild. So building images is as easy as setting up a cronjob...
> 
> Thank you for the hint! I'll look at that.

[This](https://stackoverflow.com/a/58494705/3779655) was working for me.

> > But for GUI applications I need the GUI dependencies which take some time to install and all the forwarding has to be setup. I just thought it might be easier to use x11docker for that...
> 
> Couldn't you just set up a tagged docker hub repo yourself?
> Take e.g. the `x11docker/xfce` Dockerfile, adjust it and set up a repo with several tags matching your needs. It might be based on several Debian versions as well as other distros like alpine, too.

[This](https://github.com/darkdragon-001/docker-x11) is what I did :wink: Feel free to try it out!

**Comment by huapox** [comment]
multi-tag with diff desktops, try this: 

```bash
docker  run -it --rm -p 10081:10081 -p 10089:10089 \
  --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
  --cap-add SYS_BOOT --cap-add SYS_ADMIN \
  -v /sys/fs/cgroup:/sys/fs/cgroup \
  infrastlabs/docker-headless:gnome/plas/cinna/cmate/cxfce
```

noVnc  http://192.168.0.x:10081  pw: headless
