### ISSUE TITLE
startxfce4

### ISSUE THREAD

**Issue by andrewufrank** [mviereck/dockerfile-x11docker-xfce#2]
I have observed that starting the xfce image as desktop with `x11docker --desktop x11docker/xfce` as you recommend from a console,  closes all currently running desktops (logged in). if i try to go to the normal (non docker) session with `ctrl-alt 7`I am invited to login. 
surprisingly, if I open a second docker session from another console, it does not interfere with the first docker session - i.e. I can switch betweent them with `ctrl-alt` 1 or 2. 

why does the normal (non-docker) session on console 7 stop? 

related, more fundamental question: what is the best way to start a session as a command in the docker file? here you use `CMD ["startxfce4"]`. for `mate` you have used `CMD ["mate-session"]`. it shows the same behavior (i.e. killing a running non-docker session). What are the options? 

what goes into the dockerfile if a docker session is automatically started when booting? In this case, a greeter should check the login. this was not necessary when x11docker is started from the console. 

Thank you for the examples - I learned a lot from reading!

**Comment by mviereck** [comment]
> I have observed that starting the xfce image as desktop with x11docker --desktop x11docker/xfce as you recommend from a console, closes all currently running desktops (logged in). if i try to go to the normal (non docker) session with ctrl-alt 7I am invited to login.

This must not happen!
Maybe it is an issue with the display manager. Which one do you use? gdm? lightdm? Another one? Maybe it somehow cannot handle another Xorg instance.
What is your host system? What is your regular desktop environment?

> related, more fundamental question: what is the best way to start a session as a command in the docker file? here you use CMD ["startxfce4"]. for mate you have used CMD ["mate-session"].

I don't understand the question. These are just the commands to start the respective desktop environment.

> what goes into the dockerfile if a docker session is automatically started when booting? In this case, a greeter should check the login. this was not necessary when x11docker is started from the console.

I don't understand this question, too. Do you want to start x11docker from a display manager? There is a wiki article about this.

**Comment by mviereck** [comment]
Just an idea: Do you immediately switch between the Xorg sessions?
Please try to switch to an unused black console before switching to X.

**Comment by mviereck** [comment]
Could you please answer my questions? Crashing Xorg is a serious issue that should not happen.

**Comment by andrewufrank** [comment]
sorry for not responding - I was out of town and could not easily access the web and not do anything docker related. when I am back I will check if the problem is still an issue and - if I can confirm it - reopen the question. I try to learn about docker - perhaps starting at the wrong end.
