### ISSUE TITLE
how to run a docker image in the desktop

### ISSUE THREAD

**Issue by andrewufrank** [mviereck/dockerfile-x11docker-xfce#3]
I run your xfce desktop with `--hostnet --sudouser --desktop` with the intention to run then again a dockerized application in it. Is this possible? 

I open a terminal emulator window on the desktp, but neither `x11docker` nor `docker` are known commands. They do not work with `sudo` either (`sudo command not found`). 

what additional packages must be loaded to the xfce image? I understand that dockerized applications should be able to run on top of each other - is this a misconception?

Thank you for your help!

**Comment by mviereck** [comment]
The desktop is already running in a container. You can only run commands that has been installed in the image before. `docker` and `x11docker` are installed on your host system, but not in the `x11docker/xfce` image. Neither does it contain `sudo`; you can use `su` instead.

With some tricks it is possible to run docker in a container. But I discourage it.

**Comment by mviereck** [comment]
Could you please answer my questions? Crashing Xorg is a serious issue that should not happen.
